server:
    port: 8090
    context-path: /dubbo_provider
    session:
        timeout: 300
spring:
    application:
        name: dubbo-test-provider
dubbo:
    registry:
        address: 127.0.0.1:2181
        protocol: zookeeper
    protocol:
        name: dubbo
        port: 20881
    monitor:
        protocol: registry
    scan:
        base-packages: provider.impl